/* auto-generated by scripts/sync-intro-asset.mjs — do not edit */
/* eslint-disable @typescript-eslint/no-require-imports */
export const INTRO_VIDEO_SOURCE: number = require('../../../assets/intro/universe-birth.mp4');
export const HAS_INTRO_VIDEO = true as const;
